steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/vertex-test-1-467818/gaea/db-setup:latest', '-f', 'Dockerfile.db-setup', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/vertex-test-1-467818/gaea/db-setup:latest']
images:
- 'us-central1-docker.pkg.dev/vertex-test-1-467818/gaea/db-setup:latest'